name: linux setup

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup
        run: make setup

      - name: Create symbolic links
        run: |
          rm ~/.gitconfig
          make stow

      - name: Delete symbolic links
        run: make clean
