name: macOS setup

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: brew bundle
        run: |
          brew unlink go@1.15
          bash ${GITHUB_WORKSPACE}/.config/macos/brew_bundle.sh

      - name: Create symbolic links
        run: |
          rm ~/.gitconfig
          make stow

      - name: Delete symbolic links
        run: make clean
