name: macOS setup

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove default go in path
        run: |
          ls -al /usr/local/bin/go*
          brew unlink go@1.15
          rm /usr/local/bin/go
          rm /usr/local/bin/gofmt

      - name: brew bundle
        run: bash ${GITHUB_WORKSPACE}/.config/macos/brew_bundle.sh

      - name: Create symbolic links
        run: |
          rm ~/.gitconfig
          make stow

      - name: Delete symbolic links
        run: make clean
